export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>ValentinesApp</title>
  <base href="/valentines-surprise/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-XMN7IDNH.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-XMN7IDNH.css"></noscript><style ng-app-id="ng">body[_ngcontent-ng-c1936262688]{margin:0;overflow:hidden}.valentine-card[_ngcontent-ng-c1936262688]{display:flex;flex-direction:column;justify-content:center;align-items:center;height:100vh;text-align:center;background:linear-gradient(to bottom,#ff9f9f,#ffd6d6);font-family:Dancing Script,cursive;animation:fadeIn 1.5s ease-in-out}button[_ngcontent-ng-c1936262688]{padding:15px 30px;font-size:20px;border:none;border-radius:25px;cursor:pointer;font-weight:700;transition:transform .2s,background-color .2s}button.yes[_ngcontent-ng-c1936262688]{background-color:#28a745;color:#fff}button.no[_ngcontent-ng-c1936262688]{background-color:#dc3545;color:#fff}button[_ngcontent-ng-c1936262688]:hover{transform:scale(1.1);box-shadow:0 5px 15px #0000004d}h1[_ngcontent-ng-c1936262688]{font-size:2.5rem;color:#e63946;font-family:Dancing Script,cursive}@keyframes _ngcontent-ng-c1936262688_fall{0%{transform:translateY(-100vh) rotate(0)}to{transform:translateY(100vh) rotate(720deg)}}.heart[_ngcontent-ng-c1936262688]{position:absolute;top:0;background:pink;width:20px;height:20px;clip-path:polygon(50% 0%,100% 40%,80% 100%,50% 75%,20% 100%,0% 40%);animation:_ngcontent-ng-c1936262688_fall 5s infinite linear}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click","mouseover"],[]);</script>
  <app-root ng-version="19.1.3" _nghost-ng-c1936262688 ngh="0" ng-server-context="ssg"><div _ngcontent-ng-c1936262688><div _ngcontent-ng-c1936262688 class="valentine-card"><h1 _ngcontent-ng-c1936262688>Will you be my Valentine’s date? ❤️</h1><div _ngcontent-ng-c1936262688 class="button-group"><button _ngcontent-ng-c1936262688 class="yes" jsaction="click:;">Yes</button><button _ngcontent-ng-c1936262688 class="no" jsaction="mouseover:;">No</button></div></div></div><!----><!----><audio _ngcontent-ng-c1936262688 autoplay loop><source _ngcontent-ng-c1936262688 src="assets/romantic-violin.mp3" type="audio/mp3"> Your browser does not support the audio element.
</audio></app-root>
  <script src="assets/confetti.js"></script>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="scripts-VPMHGWZW.js" defer></script><script src="main-Y44XNNCG.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"0":"t0","1":"t1"},"c":{"0":[{"i":"t0","r":1}],"1":[]}}]}</script></body></html>`;